### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by marcusmuller** [lasmaty07/NetflixToTrakt#1]
C:\Users\mmcar\Downloads\NetflixToTrakt-master>>python SyncHistoryTracktv.py
Please use your favorite mehtod to install the following module requests and simplejson to use this script

C:\Users\mmcar\Downloads\NetflixToTrakt-master>pip install simplejson
Collecting simplejson
  Downloading simplejson-3.17.3-cp39-cp39-win_amd64.whl (75 kB)
     |████████████████████████████████| 75 kB 484 kB/s
Installing collected packages: simplejson
Successfully installed simplejson-3.17.3
WARNING: You are using pip version 21.0.1; however, version 21.2.1 is available.
You should consider upgrading via the 'c:\users\mmcar\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.

C:\Users\mmcar\Downloads\NetflixToTrakt-master>>python SyncHistoryTracktv.py
Please use your favorite mehtod to install the following module requests and simplejson to use this script

**Comment by lasmaty07** [comment]
why are you installing simplejson? 

run `pip install -r requirements.txt`
